"""Local artifact audit. --regenerate also re-runs generators and PNG renderers.

Use --node /path/to/node --sharp /path/to/sharp when not installed in PATH.
"""
from pathlib import Path
import argparse
import hashlib
import json
import re
import struct
import subprocess
import sys
import xml.etree.ElementTree as ET
from urllib.parse import unquote

HERE=Path(__file__).resolve().parent
REPO=HERE.parents[1]
OPS=HERE.parent/'figure-abstraction-operations'


def generated():
    result=list((HERE/'answers').glob('*'))+list((HERE/'prompts').glob('*.md'))
    result += [HERE/n for n in ['manifest.json','measurement-report.json','geometry-checks.json','contact-sheet.png']]
    result += list(OPS.glob('*.svg'))+list(OPS.glob('*.png'))
    return sorted(p for p in result if p.is_file())


def hashes(): return {str(p.relative_to(REPO)):hashlib.sha256(p.read_bytes()).hexdigest() for p in generated()}


def main():
    parser=argparse.ArgumentParser();parser.add_argument('--regenerate',action='store_true')
    parser.add_argument('--node',default='node');parser.add_argument('--sharp')
    args=parser.parse_args();errors=[]
    (HERE/'artifact-audit.json').write_text(json.dumps({'result':'running'})+'\n')
    before=hashes()
    if args.regenerate:
        for path in [HERE/'generate.py',HERE/'verify_geometry.py',HERE/'test_measure.py',OPS/'generate.py']:
            subprocess.run([sys.executable,str(path)],check=True,cwd=REPO)
        for path in [HERE/'render.cjs',OPS/'render.cjs']:
            subprocess.run([args.node,str(path)]+([args.sharp] if args.sharp else []),check=True,cwd=REPO)
        after=hashes()
        if before!=after: errors.append('Regenerated bytes differ: '+str([k for k in before.keys()|after.keys() if before.get(k)!=after.get(k)]))
    checked=0
    for file in REPO.rglob('*.md'):
        if '.git' in file.parts or 'node_modules' in file.parts: continue
        # Template examples intentionally refer to files at a future destination.
        if 'templates' in file.relative_to(REPO).parts: continue
        raw=file.read_text()
        text=re.sub(r'```.*?```','',raw,flags=re.S)
        for target in re.findall(r'!?\[[^\]]*\]\(([^\s)]+)',text):
            target=target.strip('<>')
            if re.match(r'[a-zA-Z][\w+.-]*:',target) or target.startswith('#'): continue
            target=unquote(target.split('#')[0])
            if not target:continue
            checked+=1
            if not (file.parent/target).exists(): errors.append(f'Missing link: {file.relative_to(REPO)} -> {target}')
        if raw.startswith('---\n'):
            front=raw.split('---',2)[1]
            for value in re.findall(r'^(?:related|target_skills|prerequisites|exercises):\s*\[([^\]]*)\]',front,re.M):
                for target in value.split(','):
                    target=target.strip().strip('\"\'')
                    if target and not(file.parent/target).exists(): errors.append(f'Missing metadata path: {file} -> {target}')
    references=[p for p in (REPO/'references').rglob('*.md') if p.name!='README.md']
    research=[p for p in (REPO/'research').rglob('*.md') if p.name!='README.md']
    for file in references+research:
        raw=file.read_text()
        if not raw.startswith('---\n'): errors.append('Missing frontmatter: '+str(file));continue
        front=raw.split('---',2)[1]
        required=['title','status','tags','created','updated']
        if file in references: required+=['evidence_kind','domain','verification']
        for key in required:
            if not re.search(r'^'+key+r':\s*\S',front,re.M): errors.append(f'Missing {key}: {file}')
        status=re.search(r'^status:\s*(.+)$',front,re.M)
        if not status or status.group(1).strip().strip('\"\'') not in {'draft','ready','archived'}: errors.append('Bad status: '+str(file))
    ledger=(REPO/'research/comparisons/drawing-claim-ledger.md').read_text()
    ids=re.findall(r'^\| (C\d{2}) \|',ledger,re.M)
    if ids!=[f'C{i:02}' for i in range(1,71)]: errors.append('Claim ID sequence')
    index=(REPO/'research/README.md').read_text()
    for file in research:
        if str(file.relative_to(REPO/'research')) not in index: errors.append('Unindexed research: '+str(file))
    new_svgs=list((HERE/'answers').glob('*.svg'))+list(OPS.glob('*.svg'))
    for file in new_svgs:
        doc=ET.parse(file).getroot()
        png=file.with_suffix('.png')
        if not png.exists(): errors.append('Missing PNG: '+str(file));continue
        buf=png.read_bytes()
        if buf[:8]!=b'\x89PNG\r\n\x1a\n':errors.append('Invalid PNG: '+str(png));continue
        w,h=struct.unpack('>II',buf[16:24])
        if (w,h)!=(int(doc.attrib['width']),int(doc.attrib['height'])):errors.append('Size mismatch: '+str(file))
    counts={'references':len(references),'research':len(research),'claims':len(ids),'new_svg':len(new_svgs),
            'geometry_answer_json':len(list((HERE/'answers').glob('*.json'))),'prompt_files':len(list((HERE/'prompts').glob('*.md')))}
    if counts!={'references':67,'research':35,'claims':70,'new_svg':14,'geometry_answer_json':12,'prompt_files':24}:errors.append('Unexpected counts: '+str(counts))
    if errors:
        (HERE/'artifact-audit.json').write_text(json.dumps({'result':'fail','errors':errors},ensure_ascii=False,indent=2)+'\n')
        print('\n'.join(errors));raise SystemExit(1)
    result={'date':'2026-10-02','result':'pass','counts':counts,'local_markdown_targets_checked':checked,
            'scope':'local paths and required metadata, not every external URL or Markdown anchor',
            'regeneration_byte_identical':True if args.regenerate else None,
            'generated_files_compared':len(before) if args.regenerate else 0,
            'hashes':hashes() if args.regenerate else {}}
    (HERE/'artifact-audit.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
    print(json.dumps({k:v for k,v in result.items() if k!='hashes'},ensure_ascii=False))


if __name__=='__main__': main()
